# -*- coding: utf-8 -*-
"""atm.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105TgMA35PqaV1MlD2KQW0MwrDeijPAQJ
"""

balance = 10000
pin = 1234

entered_pin = int(input("Enter your PIN: "))

if entered_pin == pin:
    print("Welcome to ATM")

    print("1. Check Balance")
    print("2. Withdraw Money")
    print("3. Deposit Money")
    print("4. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        print("Your Balance is:", balance)

    elif choice == 2:
        amount = int(input("Enter amount to withdraw: "))
        if amount <= balance:
            balance -= amount
            print("Please collect your cash")
            print("Remaining Balance:", balance)
        else:
            print("Insufficient Balance")

    elif choice == 3:
        amount = int(input("Enter amount to deposit: "))
        balance += amount
        print("Amount Deposited Successfully")
        print("Updated Balance:", balance)

    elif choice == 4:

        print("Thank you for using ATM")

    else:
        print("Invalid Choice")

else:
    print("Wrong PIN")

balance =10000
pin=1234

entered_pin=int(input("Enter your pin no:"))
if entered_pin==pin:
  print("Welcome to Atm")

  print("1:Balance Check:")
  print("2.withdrsaw the amount:")
  print("3:Deposit your Amount")
  print("4:Exit")

  choice= int(input("Enter your choice:"))

  if choice==1:
         print("Your current balance:",balance)


  elif choice==2:
          amount=int(input ("Enter your withrdraw amount:"))
          if amount <=balance:
                balance-= amount
                print("collect your cash")
                print("Remaining amount:",balance)
          else:
            print("invalid cash")

  elif choice==3:
     amount= int(input("enter the deposit amount"))
     balance += amount
     print("deposit updatted successfully")
     print(balance)

  elif choice ==4:
     print("thanks for the Atm exit")
  else:
     print("wrong choice")


else:
 print("wrong pin")